common:
  print_sql: false
  create_initial_admin_user: true
  initial_admin_user_username: admin
  initial_admin_user_password: password
  sync_conversations_on_startup: true
  sync_conversations_regularly: true
http:
  host: 127.0.0.1
  port: 8000
  cors_allow_origins:
  - http://localhost
  - http://127.0.0.1
data:
  data_dir: ./data
  database_url: sqlite+aiosqlite:///data/database.db
  mongodb_url: mongodb://cws:password@localhost:27017
  run_migration: false
auth:
  jwt_secret: MODIFY_THIS_TO_RANDOM_SECRET
  jwt_lifetime_seconds: 86400
  cookie_max_age: 86400
  cookie_name: user_auth
  user_secret: MODIFY_THIS_TO_RANDOM_SECRET
chatgpt:
  is_plus_account: false
  chatgpt_base_url:
  ask_timeout: 600
log:
  log_dir: logs
  console_log_level: INFO
stats:
  request_counter_time_window: 2592000
  request_counts_interval: 1800
  ask_log_time_window: 604800
credentials:
  chatgpt_account_access_token:
  chatgpt_account_username:
  chatgpt_account_password:
  openai_api_key:
